### PR TITLE
Mko/componentspage-friends-friendspage

### PR DESCRIPTION
**Pull request by mko5118**
### Description

Allows user to view their current friends, pending friend requests and sent friend requests

### Changes

FRIENDS PAGE
- Update FriendsPage.js component with Friends component import

FRIENDS COMPONENT
- Add friends folder to components-page folder
- Add Friends.js component -- component logic
- Add friends.module.scss -- component styling

FRIENDS ITEM COMPONENT
- Add friends-item folder to components-page folder
- Add FriendsItem.js component -- component logic
- Add friends-item.module.scss -- component styling

REQUESTS PENDING
- Add requests-pending folder to components-page folder
- Add RequestsPending.js component -- component logic
- Add requests-pending.module.scss -- component styling

REQUESTS SENT
- Add requests-sent folder to components-page folder
- Add RequestsSent.js component -- component logic
- Add requests-sent.module.scss -- component styling

### Verification

Friends Page
image

### Trello Link

https://trello.com/c/Tv3obY8v/23-set-up-routing-front-end-client-side

### Notes

- Styling is not complete but a base setup has been implemented to look clean and allow all functions correctly
- May add a time stamp (sent ... days ago) to sent friend request card
- The logic to display the empty text for pending friend requests and sent friend requests appears to not be displaying correctly, will need to update this. This does not affect functionality of requests and pending requests being added
- All functions and links should work correctly once all Pull Requests have been merged

### CODE REVIEW

**Comment by chrisbrinkmann** [comment]
image

**Comment by mko5118** [comment]
image

**Comment by chrisbrinkmann** [comment]
Biz cas Obi Wan? He should be holding a Stella Artois.

**Comment by mko5118** [comment]
image

**Pull request merged**
